<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../DwgTranslator.Application/DwgTranslator.Application.csproj" />
    <ProjectReference Include="../DwgTranslator.Contracts/DwgTranslator.Contracts.csproj" />
    <ProjectReference Include="../DwgTranslator.Transport.Core/DwgTranslator.Transport.Core.csproj" />
    <ProjectReference Include="../DwgTranslator.Transport.Windows/DwgTranslator.Transport.Windows.csproj" />
  </ItemGroup>
</Project>
