<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/DwgTranslator.Agent/DwgTranslator.Agent.csproj" />
    <ProjectReference Include="../../src/DwgTranslator.Infrastructure.Windows/DwgTranslator.Infrastructure.Windows.csproj" />
  </ItemGroup>
</Project>
